export { technologyStacks } from "./technology-stacks"
export { productionData } from "./production"
export { developmentData } from "./development"
export { projectDir } from "./projectDir"
export { fileStandard, assemblyStandard } from "./project-standard"
export { gitStandard } from "./Git-standard"
